apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-press
  labels:
    app: word
spec:
    replicas: 2
    selector:
      matchLabels:
         app: word
    template:
      metadata:
        labels:
           app: word
      spec:
        containers:
          - name: wordpress
            image: wordpress
            env: 
              - name:  WORDPRESS_DB_HOST
                value: "db"
              - name: WORDPRESS_DB_USER
                value: "rahul"
              - name: WORDPRESS_DB_PASSWORD
                value: "admin"
              - name: WORDPRESS_DB_NAME
                value: "wpdb"
            ports:
              - containerPort: 8080  
  
