
---
apiVersion: v1
kind: Namespace
metadata:
  name: deployment
...
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
...
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
...



