apiVersion: v1
kind: Service
metadata:
  name: phpsvc
spec:
  selector:
    app: php
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8383
     nodePort: 30003
  type: NodePort                        

       


